#ifndef REG_IDS_H
#define REG_IDS_H


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!

// Modules for registers

// Begin

// Conf
// Nominal values


// Fake tic12400
#define REG_ID_FAKE_TIC12400_DI1    200
#define REG_ID_FAKE_TIC12400_DI2    201

// Blink
#define REG_ID_BLINK_Q    300

// Digital Inputs
#define REG_ID_DIGITAL_INPUTS_START    400
#define REG_ID_DIGITAL_INPUTS_STOP    401


// End

#endif /* REG_IDS_H */
