#ifndef REG_IDS_H
#define REG_IDS_H


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!

// Modules for registers

// Begin

// Conf
// Nominal values


// Blink
#define REG_ID_BLINK_Q    300


// End

#endif /* REG_IDS_H */
