#ifndef REG_LIST_DATA_H
#define REG_LIST_DATA_H


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!

// Modules for registers
#include "modules/modules.h"

// Begin
REGS_BEGIN(REG_ARRAY_NAME)

// Conf
// Nominal values


// Fake tic12400
REG(REG_ID_FAKE_TIC12400_DI1, fake_tic12400.out_di[8], REG_TYPE_U8, REG_FLAG_NONE)
REG(REG_ID_FAKE_TIC12400_DI2, fake_tic12400.out_di[9], REG_TYPE_U8, REG_FLAG_NONE)

// Blink
REG(REG_ID_BLINK_Q, blink.out_value, REG_TYPE_U32, REG_FLAG_NONE)

// Digital Inputs
REG(REG_ID_DIGITAL_INPUTS_START, digital_inputs.out_start, REG_TYPE_U8, REG_FLAG_NONE)
REG(REG_ID_DIGITAL_INPUTS_STOP, digital_inputs.out_stop, REG_TYPE_U8, REG_FLAG_NONE)


// End
REGS_END()

#define REGS_COUNT REGS_COUNT_VALUE(REG_ARRAY_NAME)

#endif /* REG_LIST_DATA_H */
